services:
  redis:
    image: redis:7-alpine
    container_name: figvibe-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1m30s
      timeout: 30s
      retries: 10
      start_period: 60s

volumes:
  redis_data:
